-- CreateTable
CREATE TABLE `User` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `username` VARCHAR(191) NOT NULL,
    `email` VARCHAR(191) NOT NULL,
    `phone` VARCHAR(191) NOT NULL,
    `passwordHash` VARCHAR(191) NOT NULL,
    `isVerified` BOOLEAN NOT NULL DEFAULT false,
    `isFirstLogin` BOOLEAN NOT NULL DEFAULT true,
    `lastLogin` TIMESTAMP(6) NULL,
    `firstName` VARCHAR(100) NULL,
    `lastName` VARCHAR(100) NULL,
    `nickname` VARCHAR(191) NOT NULL DEFAULT '',
    `displayPublicAs` VARCHAR(100) NULL,
    `website` VARCHAR(255) NULL,
    `whatsapp` VARCHAR(50) NULL,
    `biography` TEXT NULL,
    `publicAddress` VARCHAR(255) NULL,
    `facebook` VARCHAR(255) NULL,
    `twitter` VARCHAR(255) NULL,
    `linkedin` VARCHAR(255) NULL,
    `pinterest` VARCHAR(255) NULL,
    `behance` VARCHAR(255) NULL,
    `dribbble` VARCHAR(255) NULL,
    `instagram` VARCHAR(255) NULL,
    `youtube` VARCHAR(255) NULL,
    `vimeo` VARCHAR(255) NULL,
    `flickr` VARCHAR(255) NULL,
    `role` ENUM('USER', 'ADMIN') NOT NULL DEFAULT 'USER',
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    UNIQUE INDEX `User_username_key`(`username`),
    UNIQUE INDEX `User_email_key`(`email`),
    UNIQUE INDEX `User_phone_key`(`phone`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
